all : makefile1 makefile2 makefile3 makefile4 makefile5

makefile1:
	@echo "running makefile1"
	cd Ex_1; make
	cd ../
makefile2:
	@echo "running makefile2"
	cd Ex_2; make
	cd ../
makefile3:
	@echo "running makefile3"
	cd Ex_3; make
	cd ../
makefile4:
	@echo "running makefile4"
	cd Ex_4; make
	cd ../
makefile5:
	@echo "running makefile5"
	cd Ex_5; make
	cd ../
clean:
	cd Ex_1; make clean
	cd ../
	cd Ex_2; make clean
	cd ../
	cd Ex_3; make clean
	cd ../
	cd Ex_4; make clean
	cd ../
	cd Ex_5; make clean